### ISSUE TITLE
Can't convert notebook to RDF

### ISSUE THREAD

**Issue by SallyAfua** [Sheeba-Samuel/ProvBook#3] opened 2021-09-09 12:17 UTC
Hi Sheeba,

Please I tried converting my notebook to RDF but I was unable to.
Although I could see the download as RDF(.ttl) on my file's drop down menu, whenever I click on it I get the error attached.
![Provbook error](https://user-images.githubusercontent.com/50123632/132684168-bd84db60-7edc-4cda-a427-254a3b738ed4.png)

**Comment by Sheeba-Samuel** [comment] 2021-10-13 20:37
Hi Salomey,
Thanks for raising this bug. The issue is fixed in this commit: 103494e837c76219bb71901a671b344bba7a8034
It is also updated in the new release.
Regards,
Sheeba

**Closed as completed by Sheeba-Samuel** 2021-10-13 20:37 UTC
